export const PATIENTS_LIST_REQUEST = "PATIENTS_LIST_REQUEST";
export const PATIENTS_LIST_SUCCESS = "PATIENTS_LIST_SUCCESS";
export const PATIENTS_LIST_FAIL = "PATIENTS_LIST_FAIL";

export const PATIENTS_CREATE_REQUEST = "PATIENTS_CREATE_REQUEST";
export const PATIENTS_CREATE_SUCCESS = "PATIENTS_CREATE_SUCCESS";
export const PATIENTS_CREATE_FAIL = "PATIENTS_CREATE_FAIL";

export const PATIENTS_UPDATE_REQUEST = "PATIENTS_UPDATE_REQUEST";
export const PATIENTS_UPDATE_SUCCESS = "PATIENTS_UPDATE_SUCCESS";
export const PATIENTS_UPDATE_FAIL = "PATIENTS_UPDATE_FAIL";

export const PATIENTS_DELETE_REQUEST = "PATIENTS_DELETE_REQUEST";
export const PATIENTS_DELETE_SUCCESS = "PATIENTS_DELETE_SUCCESS";
export const PATIENTS_DELETE_FAIL = "PATIENTS_DELETE_FAIL";

export const PATIENTS_START_SCREEN_REQUEST = "PATIENTS_START_SCREEN_REQUEST";
export const PATIENTS_START_SCREEN_SUCCESS = "PATIENTS_START_SCREEN_SUCCESS";

export const PATIENTS_REPORT_REQUEST = "PATIENTS_REPORT_REQUEST";
export const PATIENTS_REPORT_SUCCESS = "PATIENTS_REPORT_SUCCESS";
export const PATIENTS_REPORT_FAIL = "PATIENTS_REPORT_FAIL";


